#!/usr/bin/env bash

server_config=`ls ~/.server_config`
expect_script_file="/tmp/xx.expect"

xx_help (){
    # Use colors, but only if connected to a terminal, and that terminal
    # supports them.
    if which tput >/dev/null 2>&1; then
      ncolors=$(tput colors)
    fi
    if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
        RED="$(tput setaf 1)"
        GREEN="$(tput setaf 2)"
        YELLOW="$(tput setaf 3)"
        BLUE="$(tput setaf 4)"
        BOLD="$(tput bold)"
        NORMAL="$(tput sgr0)"
    else
        RED=""
        GREEN=""
        YELLOW=""
        BLUE=""
        BOLD=""
        NORMAL=""
    fi

    printf "${GREEN}"
    echo '                      .__            '
    echo '___  _____ __  _____|  |__   ____    '
    echo '\  \/  /  |  \/  ___/  |  \_/ ___\   '
    echo ' >    <|  |  /\___ \|   Y  \  \___   '
    echo '/__/\_ \____//____  >___|  /\___  >  '
    echo '      \/          \/     \/     \/   '
    printf "${NORMAL}"

    echo "server list:"
    awk '
    BEGIN { print "Tag    Ip    Port   Name    Password"; print ""}
    { print $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5; print "" }
    END { print "useage: xx server_tag"; print "" }
    ' ${server_config}
}

check_config (){
    #check config file
    if [ ! -f ${server_config} ]; then
        xx_help
        echo "error: server_config not exits!";
        exit;
    fi
}

main(){
    # Only enable exit-on-error after the non-critical colorization stuff,
    # which may fail on systems lacking tput or terminfo
    set -e

    check_config

    server_name=$1

    #check input
    cnt=`grep ${server_name} ${server_config} | wc -l`

    if [ ${cnt} -gt 1 ]; then
        xx_help
        echo "multiple servers detected, please make it more clear!!!"
        exit
    elif [ ${cnt} -eq 0 ]; then
        xx_help
        echo "none server detected, please check your server names!"
        exit
    fi

    #split ssh params
    eval $(grep ${server_name} ${server_config} |awk '{ printf("ip=%s;port=%s;username=%s;password=%s;", $2,$3,$4,$5) }')

    #expect logic
    cat >${expect_script_file}<<EOF

trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows \$rows columns \$cols < \$spawn_out(slave,name)
} WINCH

spawn ssh -p ${port} ${username}@${ip}
expect {
        "*assword" {
            set timeout 10;
            send "${password}\n";
            exp_continue;
        }
        "*passphrase" {
            set timeout 10;
            send "${password}\r\n";
            exp_continue;
         }
        "yes/no" {
            send "yes\n";
            exp_continue;
         }
        "Last*" {
            send_user "\nlogin success on:【${server_name} ${ip}】 enjoy!\n";
         }
}
interact

EOF

    #cat ${expect_script_file} # Uncomment for debug
    expect -f ${expect_script_file} # run expect script
    rm ${expect_script_file} # remove expect script
}

if [ 1 != $# ]; then
    xx_help
else
    main $1
fi